# Generated by Django 4.2.1 on 2023-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(help_text="Enter game's full name", max_length=80, verbose_name='Game name'),
        ),
    ]
