# Generated by Django 4.2.1 on 2023-05-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_games_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name', 'surname'], 'verbose_name': ('Character',), 'verbose_name_plural': 'Characters'},
        ),
    ]
