# Generated by Django 4.2.1 on 2023-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': ('Character',), 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased'), ('Unknown', 'Unknown')], default='Unknown', help_text="Select character's status", max_length=8, verbose_name='Status'),
        ),
    ]
