# Generated by Django 4.2.1 on 2023-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_options_alter_character_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='character',
            name='affiliation',
            field=models.ManyToManyField(blank=True, to='characters.groups', verbose_name='Affiliation'),
        ),
    ]
