# Generated by Django 4.2.1 on 2023-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_affiliation_character_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload characters picture', null=True, upload_to='characters', verbose_name='Photo of character'),
        ),
    ]
