# Generated by Django 4.2.1 on 2023-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='N/A', help_text='Enter a short description', max_length=300, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
