# Generated by Django 4.2.1 on 2023-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lore',
            field=models.TextField(default='Null', help_text='Enter characters backstory/lore', verbose_name='Backstory/Lore'),
            preserve_default=False,
        ),
    ]
